### ISSUE TITLE
Validate or enforce that S3 buckets and ECR repository names are lowercase prior to plan and apply

### ISSUE THREAD

**Issue by douglasnaphas** [CDCgov/dibbs-aws#28]
We had an issue where our GitHub repo name had uppercase letters. These got into the names of one or more S3 buckets and ECR repositories. The `terraform apply` failed because the bucket name and ECR repo names had to be lowercase.

https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_Image.html specifies repositoryName needs to be lower case.
 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html specifies bucket names need to be lower case.

This was when we were trying to get this to work with Terraform Cloud, but I believe it would still be an issue.

We changed the repo name to lowercase to address it.

The fix could either be to throw some kind of error if a bucket or ECR repo would have an invalid name, validated using whatever regex is used for these names by the AWS services; or invalid names could be transformed to be valid.

**Comment by alismx** [comment]
@douglasnaphas We've added some variable validation rules to prevent strings that would break deployments. I'd like to get that merged in the next few business days which will close out this ticket. Thanks for your suggestion!
