### ISSUE TITLE
Convert dibbs-aws to a GitHub template repo

### ISSUE THREAD

**Issue by douglasnaphas** [CDCgov/dibbs-aws#30]
I'd like to look into using this as a template for non-DIBBS related apps, making use of GitHub's [template repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) feature.

This is because it has a good system worked out for creating the OIDC provider, the GitHub Actions role, and the DynamoDB and S3 resources for state file management of the role and provider.

So I would deploy from this repo using _deploy from template_, then remove the application-related code and put in my application's resources.

I also think _deploy from template_ would be a good workflow for agencies to make use of this application. It gives you a trace back to this repo in the copy (it says, like, "deployed from template <link to template>"), while not being a fork, forks being more appropriate when people want to contribute back from the copy.

**Comment by alismx** [comment]
We're discussing this change. Thanks for the suggestion. I'll update you when we've decided how to proceed.
